In [4]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val) 
        

Tensor("add_11:0", dtype=float32)
0 Cost:  21538.1 
Prediction:
 [ 19.99462128  29.10997391  26.11519241  27.12723923  24.67684746]
10 Cost:  1.9488 
Prediction:
 [ 149.81892395  185.14045715  179.85917664  194.55027771  143.68690491]
20 Cost:  1.74382 
Prediction:
 [ 150.21627808  185.60942078  180.32571411  195.05802917  144.04270935]
30 Cost:  1.73607 
Prediction:
 [ 150.22200012  185.60769653  180.32850647  195.06074524  144.03952026]
40 Cost:  1.72834 
Prediction:
 [ 150.22654724  185.60458374  180.3298645   195.06195068  144.03526306]
50 Cost:  1.72066 
Prediction:
 [ 150.2310791   185.60147095  180.33122253  195.06311035  144.03100586]
60 Cost:  1.71302 
Prediction:
 [ 150.23558044  185.59837341  180.33258057  195.0643158   144.02676392]
70 Cost:  1.70542 
Prediction:
 [ 150.24006653  185.59526062  180.3339386   195.06549072  144.02252197]
80 Cost:  1.69786 
Prediction:
 [ 150.24455261  185.59216309  180.33528137  195.06665039  144.01829529]
90 Cost:  1.69035 
Prediction:
 [ 150

850 Cost:  1.22234 
Prediction:
 [ 150.55497742  185.37785339  180.42843628  195.14915466  143.72433472]
860 Cost:  1.21736 
Prediction:
 [ 150.55857849  185.37535095  180.42950439  195.15011597  143.72088623]
870 Cost:  1.21243 
Prediction:
 [ 150.56217957  185.37287903  180.43060303  195.15109253  143.71746826]
880 Cost:  1.20748 
Prediction:
 [ 150.5657959   185.37039185  180.43167114  195.15208435  143.71405029]
890 Cost:  1.20259 
Prediction:
 [ 150.56936646  185.36790466  180.43273926  195.1530304   143.71063232]
900 Cost:  1.19771 
Prediction:
 [ 150.57293701  185.365448    180.43380737  195.15402222  143.70722961]
910 Cost:  1.19288 
Prediction:
 [ 150.57649231  185.36299133  180.43487549  195.15496826  143.70384216]
920 Cost:  1.18806 
Prediction:
 [ 150.58004761  185.36051941  180.4359436   195.15592957  143.70045471]
930 Cost:  1.18326 
Prediction:
 [ 150.58358765  185.358078    180.43701172  195.15690613  143.69708252]
940 Cost:  1.17849 
Prediction:
 [ 150.58712769  185.35

1640 Cost:  0.900557 
Prediction:
 [ 150.81158447  185.20039368  180.50508118  195.2197876   143.47866821]
1650 Cost:  0.89729 
Prediction:
 [ 150.81448364  185.19839478  180.50595093  195.22061157  143.47587585]
1660 Cost:  0.894043 
Prediction:
 [ 150.81738281  185.19639587  180.50680542  195.22142029  143.47309875]
1670 Cost:  0.890817 
Prediction:
 [ 150.82025146  185.19438171  180.50765991  195.22219849  143.4703064 ]
1680 Cost:  0.887599 
Prediction:
 [ 150.82313538  185.19241333  180.50852966  195.22303772  143.46754456]
1690 Cost:  0.884399 
Prediction:
 [ 150.82598877  185.19039917  180.5093689   195.22383118  143.46476746]
1700 Cost:  0.881199 
Prediction:
 [ 150.82887268  185.18843079  180.51022339  195.22465515  143.46200562]
1710 Cost:  0.878042 
Prediction:
 [ 150.83171082  185.1864624   180.51107788  195.22546387  143.45925903]
1720 Cost:  0.874894 
Prediction:
 [ 150.83457947  185.18449402  180.51193237  195.22625732  143.45652771]
1730 Cost:  0.871759 
Prediction:
 [ 1

In [5]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

#placeholder for a tensor that will be always fed
X=tf.placeholder(tf.float32, shape=[None,3])
Y =tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b


# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

        

0 Cost:  62958.5 
Prediction:
 [[-68.90938568]
 [-84.45288086]
 [-82.22193909]
 [-90.69593048]
 [-63.9902153 ]]
10 Cost:  3.01528 
Prediction:
 [[ 153.04432678]
 [ 182.32997131]
 [ 180.63801575]
 [ 195.55265808]
 [ 139.50009155]]
20 Cost:  2.42678 
Prediction:
 [[ 153.71006775]
 [ 183.14117432]
 [ 181.43156433]
 [ 196.41749573]
 [ 140.1210022 ]]
30 Cost:  2.41467 
Prediction:
 [[ 153.70626831]
 [ 183.14759827]
 [ 181.43217468]
 [ 196.41885376]
 [ 140.12809753]]
40 Cost:  2.40262 
Prediction:
 [[ 153.70043945]
 [ 183.15159607]
 [ 181.43040466]
 [ 196.41758728]
 [ 140.13330078]]
50 Cost:  2.39066 
Prediction:
 [[ 153.69464111]
 [ 183.15556335]
 [ 181.42860413]
 [ 196.41633606]
 [ 140.13847351]]
60 Cost:  2.37877 
Prediction:
 [[ 153.68885803]
 [ 183.15951538]
 [ 181.42684937]
 [ 196.41506958]
 [ 140.14364624]]
70 Cost:  2.36692 
Prediction:
 [[ 153.68309021]
 [ 183.16346741]
 [ 181.42504883]
 [ 196.41381836]
 [ 140.14880371]]
80 Cost:  2.35518 
Prediction:
 [[ 153.67736816]
 [ 183.167404

850 Cost:  1.61593 
Prediction:
 [[ 153.27807617]
 [ 183.44090271]
 [ 181.30062866]
 [ 196.32618713]
 [ 140.51092529]]
860 Cost:  1.60823 
Prediction:
 [[ 153.27342224]
 [ 183.4440918 ]
 [ 181.29920959]
 [ 196.32518005]
 [ 140.51507568]]
870 Cost:  1.60055 
Prediction:
 [[ 153.26876831]
 [ 183.44726562]
 [ 181.29776001]
 [ 196.32418823]
 [ 140.51922607]]
880 Cost:  1.59291 
Prediction:
 [[ 153.2641449 ]
 [ 183.45043945]
 [ 181.29634094]
 [ 196.32318115]
 [ 140.52337646]]
890 Cost:  1.58533 
Prediction:
 [[ 153.25953674]
 [ 183.45361328]
 [ 181.29493713]
 [ 196.32220459]
 [ 140.5275116 ]]
900 Cost:  1.57778 
Prediction:
 [[ 153.25492859]
 [ 183.45675659]
 [ 181.29350281]
 [ 196.32118225]
 [ 140.53161621]]
910 Cost:  1.57026 
Prediction:
 [[ 153.25030518]
 [ 183.45991516]
 [ 181.292099  ]
 [ 196.32019043]
 [ 140.53572083]]
920 Cost:  1.56281 
Prediction:
 [[ 153.2457428 ]
 [ 183.46304321]
 [ 181.29069519]
 [ 196.31919861]
 [ 140.53981018]]
930 Cost:  1.55538 
Prediction:
 [[ 153.2411499 

1880 Cost:  1.00529 
Prediction:
 [[ 152.85870361]
 [ 183.72808838]
 [ 181.17172241]
 [ 196.23602295]
 [ 140.88525391]]
1890 Cost:  1.00086 
Prediction:
 [[ 152.85517883]
 [ 183.73051453]
 [ 181.17062378]
 [ 196.23527527]
 [ 140.88839722]]
1900 Cost:  0.996471 
Prediction:
 [[ 152.85166931]
 [ 183.73292542]
 [ 181.16954041]
 [ 196.23451233]
 [ 140.89152527]]
1910 Cost:  0.992105 
Prediction:
 [[ 152.84814453]
 [ 183.73530579]
 [ 181.16845703]
 [ 196.23374939]
 [ 140.89465332]]
1920 Cost:  0.987746 
Prediction:
 [[ 152.84465027]
 [ 183.73771667]
 [ 181.16737366]
 [ 196.23300171]
 [ 140.89778137]]
1930 Cost:  0.983441 
Prediction:
 [[ 152.84117126]
 [ 183.74009705]
 [ 181.1663208 ]
 [ 196.23225403]
 [ 140.90089417]]
1940 Cost:  0.979135 
Prediction:
 [[ 152.837677  ]
 [ 183.74247742]
 [ 181.16523743]
 [ 196.23150635]
 [ 140.9039917 ]]
1950 Cost:  0.974873 
Prediction:
 [[ 152.83421326]
 [ 183.74484253]
 [ 181.16416931]
 [ 196.23077393]
 [ 140.90707397]]
1960 Cost:  0.97062 
Prediction:
 

In [12]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('lect04_data_01.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
#print(x_data.shape, x_data, len(x_data))
#print(y_data.shape, y_data)

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b

cost=tf.reduce_mean(tf.square(hypothesis-Y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


0 Cost:  66339.2 
Prediction:
 [[ -93.58185577]
 [-103.74607086]
 [-106.71671295]
 [-113.39081573]
 [ -79.81564331]
 [ -54.49623871]
 [ -83.91954803]
 [ -60.88964844]
 [ -92.01602936]
 [ -78.89818573]
 [ -81.17066193]
 [ -75.43474579]
 [-112.70174408]
 [ -97.28464508]
 [ -82.7747879 ]
 [-103.512146  ]
 [ -93.38492584]
 [-100.47835541]
 [-109.24320221]
 [ -98.42212677]
 [ -97.73252106]
 [ -95.45636749]
 [ -94.73757172]
 [-100.2583313 ]
 [-109.95471191]]
10 Cost:  21.2699 
Prediction:
 [[ 146.90209961]
 [ 185.26496887]
 [ 178.0657959 ]
 [ 196.75247192]
 [ 140.60061646]
 [ 107.99436188]
 [ 148.23194885]
 [ 111.21192932]
 [ 178.07086182]
 [ 171.25111389]
 [ 142.49343872]
 [ 145.08770752]
 [ 181.52407837]
 [ 147.31048584]
 [ 150.43881226]
 [ 189.76255798]
 [ 139.55879211]
 [ 178.12863159]
 [ 171.26446533]
 [ 152.56729126]
 [ 174.50015259]
 [ 175.67028809]
 [ 164.8190918 ]
 [ 142.22132874]
 [ 189.5793457 ]]
20 Cost:  18.0003 
Prediction:
 [[ 148.58027649]
 [ 187.25317383]
 [ 180.04014587]
 [

280 Cost:  15.5882 
Prediction:
 [[ 149.00505066]
 [ 187.05490112]
 [ 180.22244263]
 [ 198.94429016]
 [ 141.91183472]
 [ 108.63265991]
 [ 149.84616089]
 [ 112.39348602]
 [ 179.38079834]
 [ 172.05154419]
 [ 143.98991394]
 [ 146.17759705]
 [ 183.89967346]
 [ 149.45979309]
 [ 151.9329071 ]
 [ 191.49754333]
 [ 141.56724548]
 [ 180.13780212]
 [ 173.6678009 ]
 [ 154.76904297]
 [ 176.34306335]
 [ 177.24357605]
 [ 166.68339539]
 [ 144.68882751]
 [ 191.62399292]]
290 Cost:  15.5058 
Prediction:
 [[ 149.02005005]
 [ 187.0471344 ]
 [ 180.22853088]
 [ 198.94549561]
 [ 141.9039917 ]
 [ 108.61547089]
 [ 149.84620667]
 [ 112.39310455]
 [ 179.36090088]
 [ 172.01878357]
 [ 143.98783875]
 [ 146.16207886]
 [ 183.91108704]
 [ 149.47529602]
 [ 151.92848206]
 [ 191.4868927 ]
 [ 141.58061218]
 [ 180.14038086]
 [ 173.6835022 ]
 [ 154.78489685]
 [ 176.34133911]
 [ 177.2326355 ]
 [ 166.6855011 ]
 [ 144.71598816]
 [ 191.62254333]]
300 Cost:  15.4241 
Prediction:
 [[ 149.03500366]
 [ 187.03942871]
 [ 180.23461914

540 Cost:  13.6613 
Prediction:
 [[ 149.37574768]
 [ 186.86276245]
 [ 180.37271118]
 [ 198.97457886]
 [ 141.71679688]
 [ 108.20851135]
 [ 149.84939575]
 [ 112.38760376]
 [ 178.89033508]
 [ 171.24539185]
 [ 143.93988037]
 [ 145.79571533]
 [ 184.18005371]
 [ 149.84037781]
 [ 151.82614136]
 [ 191.23445129]
 [ 141.8936615 ]
 [ 180.20533752]
 [ 174.05450439]
 [ 155.15985107]
 [ 176.30281067]
 [ 176.97402954]
 [ 166.73707581]
 [ 145.35728455]
 [ 191.58769226]]
550 Cost:  13.5955 
Prediction:
 [[ 149.38920593]
 [ 186.85575867]
 [ 180.37814331]
 [ 198.97569275]
 [ 141.70965576]
 [ 108.19309998]
 [ 149.84959412]
 [ 112.38754272]
 [ 178.87251282]
 [ 171.21618652]
 [ 143.93809509]
 [ 145.78187561]
 [ 184.19018555]
 [ 149.85411072]
 [ 151.82234192]
 [ 191.22489929]
 [ 141.90536499]
 [ 180.20791626]
 [ 174.0684967 ]
 [ 155.17401123]
 [ 176.30140686]
 [ 176.96424866]
 [ 166.73907471]
 [ 145.38148499]
 [ 191.58630371]]
560 Cost:  13.5302 
Prediction:
 [[ 149.40263367]
 [ 186.84877014]
 [ 180.38356018

820 Cost:  12.0161 
Prediction:
 [[ 149.73252869]
 [ 186.67599487]
 [ 180.51629639]
 [ 199.00453186]
 [ 141.52560425]
 [ 107.80049896]
 [ 149.85655212]
 [ 112.38976288]
 [ 178.41848755]
 [ 170.47384644]
 [ 143.89305115]
 [ 145.4294281 ]
 [ 184.4467926 ]
 [ 150.20118713]
 [ 151.72738647]
 [ 190.98138428]
 [ 142.199646  ]
 [ 180.27687073]
 [ 174.4236908 ]
 [ 155.53387451]
 [ 176.26782227]
 [ 176.71488953]
 [ 166.79191589]
 [ 145.99595642]
 [ 191.55018616]]
830 Cost:  11.9643 
Prediction:
 [[ 149.74450684]
 [ 186.66967773]
 [ 180.52108765]
 [ 199.0055542 ]
 [ 141.51911926]
 [ 107.78678894]
 [ 149.8568573 ]
 [ 112.38998413]
 [ 178.40263367]
 [ 170.44799805]
 [ 143.89151001]
 [ 145.41712952]
 [ 184.45570374]
 [ 150.21321106]
 [ 151.72413635]
 [ 190.97286987]
 [ 142.20976257]
 [ 180.27938843]
 [ 174.43603516]
 [ 155.54640198]
 [ 176.26672363]
 [ 176.70617676]
 [ 166.79382324]
 [ 146.01731873]
 [ 191.54885864]]
840 Cost:  11.913 
Prediction:
 [[ 149.75645447]
 [ 186.66337585]
 [ 180.52587891]

1110 Cost:  10.6815 
Prediction:
 [[ 150.06083679]
 [ 186.5022583 ]
 [ 180.6473999 ]
 [ 199.03295898]
 [ 141.34614563]
 [ 107.42524719]
 [ 149.86720276]
 [ 112.39963531]
 [ 177.98452759]
 [ 169.76824951]
 [ 143.85131836]
 [ 145.09359741]
 [ 184.68914795]
 [ 150.52767944]
 [ 151.64051819]
 [ 190.74864197]
 [ 142.47294617]
 [ 180.34924316]
 [ 174.76043701]
 [ 155.87593079]
 [ 176.23944092]
 [ 176.47671509]
 [ 166.84561157]
 [ 146.5789032 ]
 [ 191.51312256]]
1120 Cost:  10.6412 
Prediction:
 [[ 150.07145691]
 [ 186.49659729]
 [ 180.65162659]
 [ 199.03388977]
 [ 141.34028625]
 [ 107.41309357]
 [ 149.86759949]
 [ 112.40008545]
 [ 177.97047424]
 [ 169.74546814]
 [ 143.84997559]
 [ 145.08274841]
 [ 184.69694519]
 [ 150.53814697]
 [ 151.63777161]
 [ 190.74110413]
 [ 142.48164368]
 [ 180.35169983]
 [ 174.77128601]
 [ 155.88696289]
 [ 176.23860168]
 [ 176.4690094 ]
 [ 166.84739685]
 [ 146.59768677]
 [ 191.51185608]]
1130 Cost:  10.6011 
Prediction:
 [[ 150.08206177]
 [ 186.4909668 ]
 [ 180.65583

1400 Cost:  9.63995 
Prediction:
 [[ 150.35203552]
 [ 186.34638977]
 [ 180.76268005]
 [ 199.0589447 ]
 [ 141.18367004]
 [ 107.09262848]
 [ 149.88046265]
 [ 112.415802  ]
 [ 177.599823  ]
 [ 169.14653015]
 [ 143.81555176]
 [ 144.79692078]
 [ 184.90115356]
 [ 150.81202698]
 [ 151.567276  ]
 [ 190.54237366]
 [ 142.70759583]
 [ 180.41960144]
 [ 175.05627441]
 [ 156.17730713]
 [ 176.21786499]
 [ 176.26573181]
 [ 166.89627075]
 [ 147.0914917 ]
 [ 191.47779846]]
1410 Cost:  9.60843 
Prediction:
 [[ 150.36146545]
 [ 186.34130859]
 [ 180.76641846]
 [ 199.05978394]
 [ 141.17835999]
 [ 107.0818634 ]
 [ 149.88096619]
 [ 112.41645813]
 [ 177.58737183]
 [ 169.12646484]
 [ 143.81442261]
 [ 144.78735352]
 [ 184.90795898]
 [ 150.82116699]
 [ 151.56497192]
 [ 190.53567505]
 [ 142.71507263]
 [ 180.42199707]
 [ 175.0657959 ]
 [ 156.18702698]
 [ 176.21722412]
 [ 176.25889587]
 [ 166.89796448]
 [ 147.10801697]
 [ 191.47662354]]
1420 Cost:  9.57715 
Prediction:
 [[ 150.37086487]
 [ 186.33627319]
 [ 180.77012

1690 Cost:  8.82615 
Prediction:
 [[ 150.6104126 ]
 [ 186.20651245]
 [ 180.86410522]
 [ 199.08273315]
 [ 141.03646851]
 [ 106.79769135]
 [ 149.89578247]
 [ 112.43699646]
 [ 177.25866699]
 [ 168.59867859]
 [ 143.7849884 ]
 [ 144.53477478]
 [ 185.08657837]
 [ 151.05957031]
 [ 151.50576782]
 [ 190.35948181]
 [ 142.90869141]
 [ 180.48774719]
 [ 175.31619263]
 [ 156.44290161]
 [ 176.20201111]
 [ 176.07878113]
 [ 166.94403076]
 [ 147.54223633]
 [ 191.44425964]]
1700 Cost:  8.80152 
Prediction:
 [[ 150.61878967]
 [ 186.20191956]
 [ 180.86737061]
 [ 199.08351135]
 [ 141.03163147]
 [ 106.78813934]
 [ 149.89631653]
 [ 112.43781281]
 [ 177.24760437]
 [ 168.58097839]
 [ 143.78401184]
 [ 144.52629089]
 [ 185.0925293 ]
 [ 151.06748962]
 [ 151.50382996]
 [ 190.35354614]
 [ 142.91505432]
 [ 180.49005127]
 [ 175.32455444]
 [ 156.45144653]
 [ 176.20155334]
 [ 176.07272339]
 [ 166.94560242]
 [ 147.55674744]
 [ 191.44313049]]
1710 Cost:  8.77707 
Prediction:
 [[ 150.62713623]
 [ 186.19740295]
 [ 180.87063

1950 Cost:  8.24844 
Prediction:
 [[ 150.81732178]
 [ 186.09320068]
 [ 180.9446106 ]
 [ 199.10235596]
 [ 140.91619873]
 [ 106.5616684 ]
 [ 149.91081238]
 [ 112.45935059]
 [ 176.98565674]
 [ 168.16297913]
 [ 143.76144409]
 [ 144.32571411]
 [ 185.23291016]
 [ 151.25396729]
 [ 151.45925903]
 [ 190.21313477]
 [ 143.0640564 ]
 [ 180.54678345]
 [ 175.52226257]
 [ 156.65408325]
 [ 176.19192505]
 [ 175.92927551]
 [ 166.98446655]
 [ 147.89990234]
 [ 191.41564941]]
1960 Cost:  8.22865 
Prediction:
 [[ 150.82484436]
 [ 186.08903503]
 [ 180.94752502]
 [ 199.10307312]
 [ 140.91177368]
 [ 106.55307007]
 [ 149.91140747]
 [ 112.46026611]
 [ 176.97570801]
 [ 168.14717102]
 [ 143.76060486]
 [ 144.31813049]
 [ 185.23820496]
 [ 151.26097107]
 [ 151.45762634]
 [ 190.20780945]
 [ 143.06959534]
 [ 180.54901123]
 [ 175.52970886]
 [ 156.66174316]
 [ 176.19160461]
 [ 175.92384338]
 [ 166.98597717]
 [ 147.91282654]
 [ 191.41456604]]
1970 Cost:  8.20903 
Prediction:
 [[ 150.83233643]
 [ 186.08491516]
 [ 180.95042

ValueError: Cannot feed value of shape (3,) for Tensor 'Placeholder_6:0', which has shape '(?, 3)'

In [7]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility
filename_queue=tf.train.string_input_producer(['lect04_data_01.csv','lect04_data_02.csv','lect04_data_03.csv'],shuffle=False,name='filename_queue')

reader = tf.TextLineReader()
key, value=reader.read(filename_queue)

record_defaults=[[0.],[0.],[0.],[0.]]
xy=tf.decode_csv(value,record_defaults=record_defaults)

# what is '\'?
train_x_batch, train_y_batch=\
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
    
X=tf.placeholder(tf.float32, shape=[None,3])
Y=tf.placeholder(tf.float32, shape=[None,1])


W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b

cost=tf.reduce_mean(tf.square(hypothesis-Y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

#start populating the filename queue
coord=tf.train.Coordinator()
threads=tf.train.start_queue_runners(sess=sess,coord=coord)

for step in range(5001):
    x_batch, y_batch=sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  14158.2 
Prediction:
 [[ 48.25266266]
 [ 48.80487823]
 [ 53.15052795]
 [ 53.81211853]
 [ 38.31577301]
 [ 20.92479897]
 [ 36.82830811]
 [ 22.74007607]
 [ 38.52127075]
 [ 25.87856483]]
10 Cost:  94.0453 
Prediction:
 [[ 159.22523499]
 [ 182.26100159]
 [ 184.60494995]
 [ 197.00300598]
 [ 140.09472656]
 [  96.01304626]
 [ 144.03022766]
 [ 102.23667145]
 [ 163.29652405]
 [ 141.51750183]]
20 Cost:  87.1068 
Prediction:
 [[ 159.94003296]
 [ 183.1758728 ]
 [ 185.47579956]
 [ 197.97399902]
 [ 140.78767395]
 [  96.56529999]
 [ 144.77502441]
 [ 102.81229401]
 [ 164.19207764]
 [ 142.4019165 ]]
30 Cost:  86.2744 
Prediction:
 [[ 159.91094971]
 [ 183.19622803]
 [ 185.46551514]
 [ 197.98529053]
 [ 140.79840088]
 [  96.61434937]
 [ 144.80136108]
 [ 102.85519409]
 [ 164.25137329]
 [ 142.51144409]]
40 Cost:  85.4863 
Prediction:
 [[ 159.87702942]
 [ 183.21046448]
 [ 185.44934082]
 [ 197.99003601]
 [ 140.80448914]
 [  96.65979767]
 [ 144.82273865]
 [ 102.89432526]
 [ 164.30477905]
 [ 142.6152801

470 Cost:  57.8132 
Prediction:
 [[ 158.563797  ]
 [ 183.75108337]
 [ 184.8182373 ]
 [ 198.17732239]
 [ 141.02189636]
 [  98.41745758]
 [ 145.66929626]
 [ 104.44673157]
 [ 166.37034607]
 [ 146.65148926]]
480 Cost:  57.2949 
Prediction:
 [[ 158.53646851]
 [ 183.762146  ]
 [ 184.80497742]
 [ 198.18132019]
 [ 141.02603149]
 [  98.45411682]
 [ 145.68740845]
 [ 104.47999573]
 [ 166.41340637]
 [ 146.7361145 ]]
490 Cost:  56.7815 
Prediction:
 [[ 158.50924683]
 [ 183.77314758]
 [ 184.79179382]
 [ 198.18534851]
 [ 141.03013611]
 [  98.49059296]
 [ 145.70545959]
 [ 104.51311493]
 [ 166.45628357]
 [ 146.82034302]]
500 Cost:  56.2729 
Prediction:
 [[ 158.48217773]
 [ 183.78408813]
 [ 184.77867126]
 [ 198.18933105]
 [ 141.03419495]
 [  98.52689362]
 [ 145.72346497]
 [ 104.54613495]
 [ 166.49894714]
 [ 146.9041748 ]]
510 Cost:  55.7692 
Prediction:
 [[ 158.4552002 ]
 [ 183.79496765]
 [ 184.76557922]
 [ 198.19328308]
 [ 141.03820801]
 [  98.56301117]
 [ 145.74134827]
 [ 104.5790329 ]
 [ 166.54139709

940 Cost:  38.0931 
Prediction:
 [[ 157.41407776]
 [ 184.20727539]
 [ 184.25602722]
 [ 198.35076904]
 [ 141.17837524]
 [  99.9601593 ]
 [ 146.45207214]
 [ 105.88548279]
 [ 168.18318176]
 [ 150.23197937]]
950 Cost:  37.7625 
Prediction:
 [[ 157.39242554]
 [ 184.21566772]
 [ 184.24534607]
 [ 198.35414124]
 [ 141.18095398]
 [  99.98927307]
 [ 146.46730042]
 [ 105.9134903 ]
 [ 168.21739197]
 [ 150.29997253]]
960 Cost:  37.4349 
Prediction:
 [[ 157.37086487]
 [ 184.22401428]
 [ 184.23468018]
 [ 198.35749817]
 [ 141.18347168]
 [ 100.01824188]
 [ 146.48246765]
 [ 105.94140625]
 [ 168.25141907]
 [ 150.36766052]]
970 Cost:  37.1105 
Prediction:
 [[ 157.34941101]
 [ 184.23233032]
 [ 184.22409058]
 [ 198.3608551 ]
 [ 141.18598938]
 [ 100.04707336]
 [ 146.49758911]
 [ 105.96923065]
 [ 168.28530884]
 [ 150.43502808]]
980 Cost:  36.7892 
Prediction:
 [[ 157.32807922]
 [ 184.24057007]
 [ 184.21351624]
 [ 198.36419678]
 [ 141.18843079]
 [ 100.07575226]
 [ 146.51263428]
 [ 105.99694824]
 [ 168.3190155 

1350 Cost:  26.8339 
Prediction:
 [[ 156.60896301]
 [ 184.51333618]
 [ 183.8547821 ]
 [ 198.47958374]
 [ 141.26148987]
 [ 101.04348755]
 [ 147.0327301 ]
 [ 106.95523071]
 [ 169.45613098]
 [ 152.77583313]]
1360 Cost:  26.6111 
Prediction:
 [[ 156.59133911]
 [ 184.51986694]
 [ 183.84588623]
 [ 198.48249817]
 [ 141.26300049]
 [ 101.06725311]
 [ 147.04585266]
 [ 106.97939301]
 [ 169.48405457]
 [ 152.83201599]]
1370 Cost:  26.3903 
Prediction:
 [[ 156.57377625]
 [ 184.52639771]
 [ 183.83706665]
 [ 198.4854126 ]
 [ 141.26449585]
 [ 101.09091949]
 [ 147.05892944]
 [ 107.00349426]
 [ 169.51187134]
 [ 152.88792419]]
1380 Cost:  26.1717 
Prediction:
 [[ 156.55628967]
 [ 184.53286743]
 [ 183.82826233]
 [ 198.48828125]
 [ 141.26596069]
 [ 101.11445618]
 [ 147.07192993]
 [ 107.02748871]
 [ 169.53952026]
 [ 152.943573  ]]
1390 Cost:  25.9551 
Prediction:
 [[ 156.53892517]
 [ 184.53929138]
 [ 183.81948853]
 [ 198.49116516]
 [ 141.26737976]
 [ 101.13788605]
 [ 147.08488464]
 [ 107.05141449]
 [ 169.567

1800 Cost:  18.6628 
Prediction:
 [[ 155.89689636]
 [ 184.77093506]
 [ 183.49250793]
 [ 198.60076904]
 [ 141.30915833]
 [ 102.00454712]
 [ 147.57806396]
 [ 107.96212769]
 [ 170.58534241]
 [ 155.06138611]]
1810 Cost:  18.5187 
Prediction:
 [[ 155.88284302]
 [ 184.77586365]
 [ 183.48526001]
 [ 198.60324097]
 [ 141.30976868]
 [ 102.02355194]
 [ 147.58920288]
 [ 107.98272705]
 [ 170.60766602]
 [ 155.10691833]]
1820 Cost:  18.3759 
Prediction:
 [[ 155.86885071]
 [ 184.78077698]
 [ 183.47805786]
 [ 198.60571289]
 [ 141.31039429]
 [ 102.04244995]
 [ 147.60031128]
 [ 108.00325775]
 [ 170.62988281]
 [ 155.15226746]]
1830 Cost:  18.2346 
Prediction:
 [[ 155.85493469]
 [ 184.78562927]
 [ 183.47087097]
 [ 198.60816956]
 [ 141.31098938]
 [ 102.06127167]
 [ 147.6113739 ]
 [ 108.02371216]
 [ 170.6519928 ]
 [ 155.19735718]]
1840 Cost:  18.0946 
Prediction:
 [[ 155.84111023]
 [ 184.79046631]
 [ 183.46372986]
 [ 198.61062622]
 [ 141.31156921]
 [ 102.07998657]
 [ 147.62240601]
 [ 108.0440979 ]
 [ 170.673

2220 Cost:  13.672 
Prediction:
 [[ 155.36424255]
 [ 184.95233154]
 [ 183.21510315]
 [ 198.69767761]
 [ 141.32241821]
 [ 102.72597504]
 [ 148.01350403]
 [ 108.76796722]
 [ 171.43295288]
 [ 156.80195618]]
2230 Cost:  13.5764 
Prediction:
 [[ 155.35289001]
 [ 184.95602417]
 [ 183.20910645]
 [ 198.69979858]
 [ 141.32240295]
 [ 102.7413559 ]
 [ 148.02308655]
 [ 108.78574371]
 [ 171.45101929]
 [ 156.83937073]]
2240 Cost:  13.4817 
Prediction:
 [[ 155.34162903]
 [ 184.95976257]
 [ 183.20318604]
 [ 198.70193481]
 [ 141.32243347]
 [ 102.75666809]
 [ 148.03265381]
 [ 108.80345917]
 [ 171.46902466]
 [ 156.87661743]]
2250 Cost:  13.3879 
Prediction:
 [[ 155.33041382]
 [ 184.96342468]
 [ 183.19723511]
 [ 198.70405579]
 [ 141.32241821]
 [ 102.77189636]
 [ 148.04219055]
 [ 108.82112122]
 [ 171.48690796]
 [ 156.91369629]]
2260 Cost:  13.2951 
Prediction:
 [[ 155.31924438]
 [ 184.96707153]
 [ 183.19134521]
 [ 198.70617676]
 [ 141.3223877 ]
 [ 102.78705597]
 [ 148.05166626]
 [ 108.83872223]
 [ 171.5047

2640 Cost:  10.3673 
Prediction:
 [[ 154.93505859]
 [ 185.08840942]
 [ 182.98591614]
 [ 198.78131104]
 [ 141.31318665]
 [ 103.30950928]
 [ 148.38877869]
 [ 109.46406555]
 [ 172.11851501]
 [ 158.23190308]]
2650 Cost:  10.3042 
Prediction:
 [[ 154.92593384]
 [ 185.09117126]
 [ 182.98097229]
 [ 198.78314209]
 [ 141.31272888]
 [ 103.32192993]
 [ 148.39706421]
 [ 109.47943115]
 [ 172.13313293]
 [ 158.26263428]]
2660 Cost:  10.2416 
Prediction:
 [[ 154.91685486]
 [ 185.09391785]
 [ 182.9760437 ]
 [ 198.7849884 ]
 [ 141.31228638]
 [ 103.33430481]
 [ 148.40531921]
 [ 109.49476624]
 [ 172.1476593 ]
 [ 158.29321289]]
2670 Cost:  10.1797 
Prediction:
 [[ 154.90782166]
 [ 185.09663391]
 [ 182.97114563]
 [ 198.78683472]
 [ 141.31181335]
 [ 103.34661102]
 [ 148.41352844]
 [ 109.51002502]
 [ 172.16210938]
 [ 158.32365417]]
2680 Cost:  10.1184 
Prediction:
 [[ 154.89884949]
 [ 185.09934998]
 [ 182.96626282]
 [ 198.78866577]
 [ 141.31135559]
 [ 103.35884857]
 [ 148.42172241]
 [ 109.52523804]
 [ 172.176

3070 Cost:  8.14784 
Prediction:
 [[ 154.58291626]
 [ 185.19047546]
 [ 182.79244995]
 [ 198.85528564]
 [ 141.28663635]
 [ 103.79044342]
 [ 148.72003174]
 [ 110.07981873]
 [ 172.68353271]
 [ 159.43139648]]
3080 Cost:  8.10674 
Prediction:
 [[ 154.57562256]
 [ 185.19244385]
 [ 182.7883606 ]
 [ 198.85684204]
 [ 141.2858429 ]
 [ 103.80042267]
 [ 148.72715759]
 [ 110.09309387]
 [ 172.69522095]
 [ 159.45649719]]
3090 Cost:  8.06606 
Prediction:
 [[ 154.56837463]
 [ 185.19441223]
 [ 182.78431702]
 [ 198.85844421]
 [ 141.28504944]
 [ 103.81031799]
 [ 148.73425293]
 [ 110.10631561]
 [ 172.70687866]
 [ 159.48149109]]
3100 Cost:  8.02581 
Prediction:
 [[ 154.56118774]
 [ 185.19638062]
 [ 182.7802887 ]
 [ 198.86001587]
 [ 141.28425598]
 [ 103.82019043]
 [ 148.74134827]
 [ 110.11949921]
 [ 172.71846008]
 [ 159.50636292]]
3110 Cost:  7.98593 
Prediction:
 [[ 154.55401611]
 [ 185.19833374]
 [ 182.77629089]
 [ 198.86161804]
 [ 141.28347778]
 [ 103.83000183]
 [ 148.74841309]
 [ 110.13264465]
 [ 172.729

3490 Cost:  6.73525 
Prediction:
 [[ 154.30821228]
 [ 185.26139832]
 [ 182.63661194]
 [ 198.91772461]
 [ 141.24876404]
 [ 104.16751099]
 [ 148.99945068]
 [ 110.6003952 ]
 [ 173.1264801 ]
 [ 160.39065552]]
3500 Cost:  6.70844 
Prediction:
 [[ 154.30239868]
 [ 185.26280212]
 [ 182.63327026]
 [ 198.9190979 ]
 [ 141.24775696]
 [ 104.17551422]
 [ 149.00563049]
 [ 110.61191559]
 [ 173.13587952]
 [ 160.41127014]]
3510 Cost:  6.68191 
Prediction:
 [[ 154.29660034]
 [ 185.26417542]
 [ 182.62991333]
 [ 198.92047119]
 [ 141.24673462]
 [ 104.18348694]
 [ 149.01177979]
 [ 110.6233902 ]
 [ 173.14523315]
 [ 160.4317627 ]]
3520 Cost:  6.65564 
Prediction:
 [[ 154.29086304]
 [ 185.26556396]
 [ 182.62660217]
 [ 198.92185974]
 [ 141.24572754]
 [ 104.19141388]
 [ 149.01791382]
 [ 110.63484192]
 [ 173.15455627]
 [ 160.45219421]]
3530 Cost:  6.62965 
Prediction:
 [[ 154.28512573]
 [ 185.26689148]
 [ 182.62327576]
 [ 198.92321777]
 [ 141.24468994]
 [ 104.19929504]
 [ 149.02401733]
 [ 110.64624786]
 [ 173.163

3930 Cost:  5.78249 
Prediction:
 [[ 154.07984924]
 [ 185.31190491]
 [ 182.50230408]
 [ 198.97434998]
 [ 141.20050049]
 [ 104.48284912]
 [ 149.25236511]
 [ 111.07261658]
 [ 173.49690247]
 [ 161.21130371]]
3940 Cost:  5.76553 
Prediction:
 [[ 154.07527161]
 [ 185.31282043]
 [ 182.4995575 ]
 [ 198.97555542]
 [ 141.19934082]
 [ 104.48920441]
 [ 149.25767517]
 [ 111.08256531]
 [ 173.50437927]
 [ 161.2280426 ]]
3950 Cost:  5.74872 
Prediction:
 [[ 154.07070923]
 [ 185.31370544]
 [ 182.49681091]
 [ 198.97674561]
 [ 141.19815063]
 [ 104.49551392]
 [ 149.26296997]
 [ 111.09248352]
 [ 173.51177979]
 [ 161.2447052 ]]
3960 Cost:  5.73209 
Prediction:
 [[ 154.06617737]
 [ 185.31459045]
 [ 182.49407959]
 [ 198.97793579]
 [ 141.19699097]
 [ 104.50179291]
 [ 149.26826477]
 [ 111.10236359]
 [ 173.51916504]
 [ 161.2612915 ]]
3970 Cost:  5.71565 
Prediction:
 [[ 154.06167603]
 [ 185.31547546]
 [ 182.49137878]
 [ 198.97911072]
 [ 141.19580078]
 [ 104.50804138]
 [ 149.27352905]
 [ 111.11222076]
 [ 173.526

4340 Cost:  5.21504 
Prediction:
 [[ 153.91137695]
 [ 185.34184265]
 [ 182.39909363]
 [ 199.02018738]
 [ 141.15045166]
 [ 104.71709442]
 [ 149.45664978]
 [ 111.45488739]
 [ 173.77204895]
 [ 161.83660889]]
4350 Cost:  5.20407 
Prediction:
 [[ 153.9077301 ]
 [ 185.34239197]
 [ 182.39680481]
 [ 199.02122498]
 [ 141.14920044]
 [ 104.7221756 ]
 [ 149.46128845]
 [ 111.46357727]
 [ 173.77804565]
 [ 161.85038757]]
4360 Cost:  5.19325 
Prediction:
 [[ 153.90411377]
 [ 185.34295654]
 [ 182.39454651]
 [ 199.02227783]
 [ 141.1479187 ]
 [ 104.72724915]
 [ 149.46592712]
 [ 111.47225189]
 [ 173.78399658]
 [ 161.86410522]]
4370 Cost:  5.18249 
Prediction:
 [[ 153.90049744]
 [ 185.3434906 ]
 [ 182.39227295]
 [ 199.02330017]
 [ 141.14666748]
 [ 104.73227692]
 [ 149.47053528]
 [ 111.48088837]
 [ 173.78991699]
 [ 161.8777771 ]]
4380 Cost:  5.17191 
Prediction:
 [[ 153.89692688]
 [ 185.34402466]
 [ 182.39002991]
 [ 199.02433777]
 [ 141.145401  ]
 [ 104.73728943]
 [ 149.47512817]
 [ 111.48950195]
 [ 173.795

4780 Cost:  4.83047 
Prediction:
 [[ 153.76893616]
 [ 185.35984802]
 [ 182.307724  ]
 [ 199.06297302]
 [ 141.09367371]
 [ 104.91674042]
 [ 149.64710999]
 [ 111.81201935]
 [ 174.00657654]
 [ 162.38520813]]
4790 Cost:  4.82373 
Prediction:
 [[ 153.76609802]
 [ 185.36012268]
 [ 182.30584717]
 [ 199.06388855]
 [ 141.09236145]
 [ 104.92073059]
 [ 149.65112305]
 [ 111.81955719]
 [ 174.01127625]
 [ 162.39640808]]
4800 Cost:  4.81708 
Prediction:
 [[ 153.76327515]
 [ 185.36039734]
 [ 182.3039856 ]
 [ 199.06478882]
 [ 141.09104919]
 [ 104.92471313]
 [ 149.65512085]
 [ 111.82707214]
 [ 174.01596069]
 [ 162.40753174]]
4810 Cost:  4.8105 
Prediction:
 [[ 153.76046753]
 [ 185.36064148]
 [ 182.30212402]
 [ 199.06568909]
 [ 141.08973694]
 [ 104.92867279]
 [ 149.65911865]
 [ 111.83457184]
 [ 174.02059937]
 [ 162.41860962]]
4820 Cost:  4.80398 
Prediction:
 [[ 153.75767517]
 [ 185.36090088]
 [ 182.30029297]
 [ 199.0665741 ]
 [ 141.08843994]
 [ 104.9325943 ]
 [ 149.6631012 ]
 [ 111.84203339]
 [ 174.0252

In [14]:
filename_queue